spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
logging:
  level:
    org: ERROR