server:
  port: 8073
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql:///db1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTime=UTC
    username: test
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-spock-test
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*/*.xml
