server:
  port: 8080
spring:
  application:
    name: provider
  config:
    import:
      - optional:nacos:provider.yml
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: localhost:8848
        namespace: test
        group: DEFAULT_GROUP
      config:
        # 指定Nacos配置中心的地址
        server-addr: localhost:8848
        namespace: test
        group: DEFAULT_GROUP
        file-extension: yml
    sentinel:
      transport:
        #sentinel控制台的请求地址
        dashboard: localhost:8849