spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:nacos:gateway.yml
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: localhost:8848
        namespace: test
        group: DEFAULT_GROUP
        enabled: true
      config:
        # 指定Nacos配置中心的地址
        server-addr: localhost:8848
        namespace: test
        group: DEFAULT_GROUP
        file-extension: yml
    sentinel:
      transport:
        #sentinel控制台的请求地址
        dashboard: localhost:8849
      #配置限流之后的响应内容
#      scg:
#        fallback:
#          # 两种模式：一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
#          mode: response
#          # 响应的状态
#          response-status: 426
#          # 响应体
#          response-body: '{"code": 426,"message": "限流了，稍后重试！"}'
#      eager: true
#      datasource:
#        r1:
#          nacos:
#            # nacos地址
#            server-addr: localhost:8848
#            # nacos中配置文件的data-id
#            data-id: gateway-api-sentinel
#            # nacos 分组
#            group-id: DEFAULT_GROUP
#            # 规则类型 流控
#            rule-type: flow
#        r2:
#          nacos:
#            server-addr: localhost:8848
#            data-id: gateway-api-sentinel-degrade
#            group-id: DEFAULT_GROUP
#            rule-type: degrade


    loadbalancer:
      nacos:
        enabled: true
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      globalcors:
#        #全部允许
#        cors-configurations:
#          '[/**]':
#            #是否允许cookie跨域  true允许
#            allowCredentials: true
#            #允许跨域的url * 则允许全部
#            allowedOriginPatterns: '*'
#            # 允许跨域的方法 * 则全部
#            allowedMethods: '*'
#            alloweHeaders: '*'
#      routes:
#        - id: 服务提供者
#          uri: lb://provider
#          predicates:
#            - Path=/provider/**
#          filters:
#            - StripPrefix=1