server:
  port: 8085
spring:
  application:
    name: mall-server
  profiles:
    active: prod
  aop:
    auto: true

  servlet:
    multipart:
      # maxFileSize 单个数据大小
      max-file-size: 1024MB
      # maxRequestSize 是总数据大小
      max-request-size: 1024MB

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

