#端口
server:
  port: 8204

spring:
  application:
    name: zuul-server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8200/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true

zuul:
  routes:
    order-server:
      path: /order/**
      url: http://localhost:8201/
    user-server:
      path: /auth/**
      url: http://localhost:8202/
  retryable: true
  add-host-header: true
  #不过滤HTTP请求头信息
  sensitive-headers:

