server:
  port: 8201

spring:
  application:
    name: order-server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8200/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
