server:
  port: 9071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: test
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    # 开启publisher-confirm，确认消息已发送到队列(Queue)，有以下可选值
    # simple：同步等待confirm结果，直到超时
    # correlated：异步回调，定义ConfirmCallback。mq返回结果时会回调这个ConfirmCallback
    # NONE：默认不开启
    publisher-confirm-type: correlated
    # 开启publish-return功能。确认消息已发送到交换机(Exchange)，可以定义ReturnCallback
    # true：调用ReturnCallback
    # false：直接丢弃消息
    publisher-returns: true
    #只要抵达队列,以异步发送优先回调retuDrnConfirm
    template:
      mandatory: true
    #默认客户端接收到消息自动ack, acknowledge修改为manual 开启手动确认
    listener:
      type: direct
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
mybatis:
  typeAliasesPackage: rabbitmq.entity
  mapperLocations: classpath:mybatis/mapper/*.xml
  logging:
    level:
      com.rabbitmq.mapper: debug
