spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      partitioner-class: kafka.sboot.CustomizePartitioner
      properties:
        partitioner:
          class: kafka.sboot.CustomizePartitioner
    consumer:
      group-id: springboot-groupid
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
